### ISSUE TITLE
Create get started guide 

### ISSUE THREAD

**Issue by Bayernatoor** [bisq-network/projects#26]
The Get started guide is now complete. Feedback on it would be great. For the most part i've transcribed what was on docs.bisq.network and added or refined the information. 

Most use cases are quick and to the point. The Take an offer use case is a tad longer but it is a more detailed use case and requires a longer walk through. 

Please advise if this issue would be better off in a different location such as /wiki or /support

**Comment by cbeams** [comment]
> Please advise if this issue would be better off in a different location such as /wiki or /support

Sorry I missed this when you first added it, @Bayernatoor. Yeah, bisq-network/wiki would be a better location, as work isn't about a project.

I'll close this out now, feel free to add a comment to the new issue here when you create it.
