### ISSUE TITLE
Add Buy-Monero Keybase channel on Bisq for fiat trading pairs using BSQ bonds as the security deposit

### ISSUE THREAD

**Issue by pazza83** [bisq-network/projects#56]
## Description

Following on from my proposal to [Add Monero to fiat trading pairs using BTC as the security deposit (multi-sig)](https://github.com/bisq-network/projects/issues/50)

I thought I would take a minimal resource approach to propose using a buy-monero Keybase channel to establish if there is a good demand for the service.

This proposal is to create a buy-monero Keybase channel using BSQ reputation bonds as the security deposit.

The previous proposal [Use Keybase to increase accessibility to Bisq for new traders with no funds for security deposit, trading and mining fees](https://github.com/bisq-network/proposals/issues/283) has been running well since inception a few months ago and also spawned the [Buy-BSQ channel](https://github.com/bisq-network/proposals/issues/308) which is quickly getting adoption.

## Rationale

The reasons for adding a buy-monero channel on keybase are as follows:

- It would allow the creation of a minimal viable product to see if there is a market for people looking to Buy XMR using fiat on Bisq.
- Set up would take less than a day. Just need to write a wiki, create a channel, set up some trade rules etc
- It would be a good test case for BSQ bonds (they might need a bit of development to scale this intended use case)
- I think it fits in well with the other OTC use cases being discussed Sisq / Misq etc
- If successful it would allow for appropriate resources to go into developing on this to be included in Bisq  / [Sisq](https://github.com/bisq-network/proposals/issues/331#) / [Misq](https://github.com/bisq-network/proposals/issues/330#) etc and there would already be am established user base.
- XMR/BTC is the most liquid market on Bisq. This market generates more revenue for Bisq than all of the other markets combined. Efforts are being made with atomic swaps that when/if implemented will make the future of this market, and the revenue generated from it, uncertain.
- Being able to use Bisq for XMR/Fiat trades is overwhelming popular with Monero community. See my recent Reddit Post [Would you like to be able to use Bisq to buy Monero directly with fiat](https://www.reddit.com/r/Monero/comments/micevf/would_you_like_to_be_able_to_use_bisq_to_buy/)?

## Criteria for delivery

The following would be delivered:

- buy-monero Keybase channel
- Decide on appropriate limits with feedback from community
- Decide on if the channel will be for buying and selling
- Creation of an Informal Market for XMR Trades wiki similar to https://bisq.wiki/Informal_Market_for_Small_BTC_Trades
- Pinned message on channel linking to wiki / warning of Risk
- Discussion with stakeholders about the current [suitability / limitation of the BSQ reputation bonds](https://github.com/bisq-network/growth/issues/243#issuecomment-830930128) for such a system
- Creation of an BSQ reputation bond wiki
- Some promotion of the channel within established Bisq social channels

## Measures of success

This is an experiment to see if there is user demand for fiat/monero trades. Success would be determining the demand.

I would propose a review in 6 months after launch.

I also think lessons from this channel could feed into the discussion about Bisq / Misq / Sisq and the use of BSQ reputation bonds as security.

## Risks

The following are risks:

- Relies on trust and reputation of the traders. This is not what Bisq is built on.
- BSQ reputation bonds might be inadequate for this usage
- Reputation damage for Bisq if things go wrong
- No mediation if things go wrong for traders
- There is risk future trades may occur off Keybase.
- No KYC Fiat / XMR trades may potentially be seen as a higher risk for the fiat traders than with BTC?

## Estimates

This would not cost Bisq anything in terms of my time, as it could be done as part of my existing roles.

## Notes

This project would not intially generate any revenue for the DAO. It would just be to see the size of the potential market.

**Comment by viperperidot** [comment]
I just want to add a potential side-issue to this proposal, I think if we start using Keybase for active trading more it will become inevitable to be flagged at some point and potentially shutdown. I think for this reason and to secure a main chatting platform for bisq development we should be looking at migrating to a more censorship resistant platform, before we have to do so in reaction to something. I think Matrix is probably the best choice because of the ability to maintain our 'channels', this function is available on Matrix. Plus users can run their own Matrix instance/node and it is very censorship resistant from what I can tell. (Sorry not trying to hijack this issue, maybe I should create a new issue altogether.)

**Comment by Akira45-0** [comment]
What about trading XMR for stablecoins? Could it be included in this proposal?

**Comment by MwithM** [comment]
I don't see why stablecoins can't be included, as long as there is someone to take that offer. On the BSQ channel I'm open to sell BSQ for LN, liquid, RSK and I could include DOC as well.
Maybe this project has been already overseeded by the [Sisq](https://github.com/bisq-network/proposals/issues/331) spreadsheet.

**Comment by pazza83** [comment]
Closing as think this would have been better placed as a proposal rather than a project. 

Also lack of support for this means I will hold off on opening it up as a proposal.
