### ISSUE TITLE
Establish support knowledge base

### ISSUE THREAD

**Issue by cbeams** [bisq-network/projects#6]
- [ ] @Bisq-knight to add two draft KB articles
- [ ] @m52go to take a look, provide any initial editorial feedback
- [ ] @cbeams to add category info and announce to @bisq-network/support

**Comment by m52go** [comment]
Is there any place we can put wiki contribution guidelines/suggestions? Maybe just create a new page for it?

I'm particularly interested in specifying that screenshots should omit the OS window border, since everyone runs something different, and to use the same template for all arrows (I have one I've used for all arrows on docs.bisq.network).

Disregard if this isn't a viable/appropriate idea for a wiki.

**Comment by cbeams** [comment]
> Is there any place we can put wiki contribution guidelines/suggestions? Maybe just create a new page for it?

Just a new page is fine for a start. See 

 - https://en.wikipedia.org/wiki/Category:Wikipedia_style_guidelines
 - https://en.wikipedia.org/wiki/Wikipedia:List_of_guidelines

for reference. Perhaps a page simply titled https://bisq.wiki/Guidelines would be fine for now, simply listing out the various guidelines and rules we'd like to establish.



> I'm particularly interested in specifying that screenshots should omit the OS window border, since everyone runs something different

True, but in my experience, the convenience of CMD-SHIFT-4-SPACE whole-window screenshots on macOS are important. And they look very attractive because they capture the drop shadow. I'm not opposed to a style guideline that says that all such screenshots should crop out window trim and shadows, but I'm not sure the end result will actually be better for it. If someone does a guide from ubuntu and captures the look and feel there, and most others do it from macOS, it's not the biggest deal to me personally. Also, some articles may include screenshots of non-Bisq windows, e.g. finder/explorer windows, and there is no way to hide the os-specificity there. Again, I don't have a very strong opinion on this.

> and to use the same template for all arrows (I have one I've used for all arrows on docs.bisq.network).

Seems like a good idea. Just wonder if there's actually a common toolset that people will be able to use. I've always liked using Skitch for quickly marking up screenshots. But whatever you see fit.

**Comment by cbeams** [comment]
Closing as superseded by #8. Regarding the (lack of) need for a specific "Knowledge Base" within the wiki, see yesterday's screencast on wiki organization at bisq-network/wiki#16.
